#!/usr/bin/env python3
"""Verify ML-DSA-65 test vectors (Python).

Reads mldsa65_vectors.json and verifies the signature using the Python
ML-DSA implementation.  This acts as a sanity check that the vectors
generated by generate_vectors.py are well-formed.

Usage:
    PYTHONPATH=python python interop/verify_python.py
"""

import json
import os
import sys

_repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_repo_root, "python"))

from mldsa import verify, ML_DSA_65  # noqa: E402

INTEROP_DIR = os.path.dirname(os.path.abspath(__file__))
VECTORS_FILE = os.path.join(INTEROP_DIR, "mldsa65_vectors.json")


def main() -> None:
    print("=== ML-DSA-65 verification (Python) ===")

    with open(VECTORS_FILE) as f:
        vectors = json.load(f)

    pk = bytes.fromhex(vectors["pk"])
    msg = bytes.fromhex(vectors["msg"])
    sig = bytes.fromhex(vectors["sig"])

    print(f"  algorithm : {vectors['algorithm']}")
    print(f"  pk size   : {len(pk)} bytes")
    print(f"  msg size  : {len(msg)} bytes")
    print(f"  sig size  : {len(sig)} bytes")

    ok = verify(pk, msg, sig, ML_DSA_65)

    if ok:
        print("  result    : PASS")
    else:
        print("  result    : FAIL")
        sys.exit(1)


if __name__ == "__main__":
    main()
